/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface OrderRecord {
  'rental' : string,
  'status' : string,
  'buyerEmail' : string,
  'buyerAddress' : string,
  'createdAt' : Time,
  'buyerPhone' : string,
  'buyer' : Principal,
}
export interface Rental {
  'title' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'phone' : string,
  'price' : [] | [bigint],
  'location' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptOrder' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[string, string, string, string], bigint>,
  'createRental' : ActorMethod<
    [string, string, string, [] | [bigint], string, string, ExternalBlob],
    string
  >,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'deleteRental' : ActorMethod<[string], undefined>,
  'getBuyerOrders' : ActorMethod<
    [],
    Array<[bigint, OrderRecord, ExternalBlob, string, [] | [bigint]]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[bigint], OrderRecord>,
  'getOwnerOrders' : ActorMethod<
    [],
    Array<[bigint, OrderRecord, string, Principal, string, string, string]>
  >,
  'getRental' : ActorMethod<[string], Rental>,
  'getRentals' : ActorMethod<[bigint, bigint], Array<Rental>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchRentals' : ActorMethod<[string], [bigint, Array<Rental>]>,
  'updateRental' : ActorMethod<
    [string, string, string, [] | [bigint], string, string, ExternalBlob],
    Rental
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];